name: Test suite

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: php:${{ matrix.php }}
    strategy:
      matrix:
        php: ['7.1.33-cli-alpine', '7.2.24-cli-alpine', '7.3.11-cli-alpine']

    steps:
    - name: PHP Version
      run: php -v

    - name: Install composer
      run: |
        EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
        then
            >&2 echo 'ERROR: Invalid installer signature'
            rm composer-setup.php
            exit 1
        fi

        php composer-setup.php --install-dir=/bin --filename=composer
        RESULT=$?
        rm composer-setup.php
        exit $RESULT

    - name: Checkout
      uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate
#
#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress --no-suggest
#
#    - name: Test
#      run: make tests
