name: Test suite

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php: ['7.1', '7.2', '7.3']

    steps:
    - uses: actions/checkout@v1

    - name: PHP Version
      run: php -v

#    - name: Validate composer.json and composer.lock
#      run: composer validate
#
#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress --no-suggest
#
#    - name: Test
#      run: make tests
